sed -n \
    -e 's/\.method /#.method /p' \
    -e 's/\.class /#.class /p' \
    -e 's/\.super /#.super /p' \
    -e 's/\.source /#.source /p' \
    -e 's/\.field /#.field /p' \
    -e 's/\.implements /#.implements /p' \
    -e 's/\.method /#.method /p' \
    -e '/\.locals /p' \
    -e '/const[ -/]/p' \
    -e '/\.local /p' \
    -e '/\.param /p' \
    -e '/\.line /p' \
    -e '/invoke-/{p;d;}' \
    -e '/new-instance/{p;d;}' \
    -e '/move-exception/{p;d;}' \
    -e '/catch/{p;d;}' \
    -e '/try_/{p;d;}' $1
